// ======= DO NOT EDIT THIS FILE ============

import java.io.*;
import java.util.*;

class Main {

    public static void main(String args[]) throws Exception {
        MyTree t = new MyTree();
        t.load();
        int choice;
        Scanner sca = new Scanner(System.in);
        System.out.println(" 1. Test f1 - compute height");
        System.out.println(" 2. Test f2 - count nodes");
        System.out.println(" 3. Test f3 - count leaf nodes");
        System.out.println(" 4. Test f4 - compute sum of nodes ");
        System.out.println(" 5.Test f5 - find max value ");
        System.out.println(" 6.Test f6 - PreOrder traverse ");
        System.out.println(" 7.Test f7 - InOrder traverse ");
        System.out.println(" 8.Test f8 - PostOrder traverse ");
        System.out.print("    Your selection (1 -> 5): ");
        choice = sca.nextInt();
        sca.nextLine();
        int r;
        switch (choice) {
            case 1:
                System.out.println("Height:");
                r = t.f1();
                System.out.println(r);
                break;
            case 2:
                System.out.println("Count nodes:");
                r = t.f2();
                System.out.println(r);
                break;
            case 3:
                System.out.println("Count leaf nodes:");
                r = t.f3();
                System.out.println(r);
                break;
            case 4:
                System.out.println("Sum of nodes:");
                r = t.f4();
                System.out.println(r);
                break;
            case 5:
                System.out.println("Find max");
                r = t.f5();
                System.out.println(r);
                break;
            case 6:
                System.out.println("PreOrder traverse:");
                t.f6();
                break;
            case 7:
                System.out.println("PostOrder traverse: ");
                t.f7();
                break;
            case 8:
                System.out.println("InOrder traverse: ");
                t.f8();
                break;
            default:
                System.out.println("Wrong selection");
        }
        System.out.println();
    }
}
